version: '3.3'
services:
 dumbplay-fe:
   container_name: dumbplay-fe
   image: dumbplay-fe-alpine:0.5
   stdin_open: true
   ports:
     - 3000:3000
   volumes:
     - "~/dumbplay-frontend/src/config/api.js:/wayshub-fe/src/config/api.js"
